### ISSUE TITLE
'note-transpose' is not in the npm registry

### ISSUE THREAD

**Issue by yoeran** [danigb/tonal#1]
Hi! I just wanted to try out your library but ran into an error during npm install.

The error I get is this:
```bash
npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/note-transpose
npm ERR! 404
npm ERR! 404 'note-transpose' is not in the npm registry.
```

From your NPM registry page I found that the `note-transpose` module has an npm invalid flag.
Also the link to the repository is no longer available on github.

**Comment by danigb** [comment]
Yes, sorry. I've updated the package dependencies in the npm registry. Tell me if it works.

**Comment by yoeran** [comment]
Quick response thanks! Installation works like a charm again. Will try the package later this week.
