### ISSUE TITLE
Incorrect version published to @latest

### ISSUE THREAD

**Issue by nickroberts404** [danigb/tonal#102]
I was having trouble importing anything from `tonal`,  then realized I had version `v3.0.0-alpha1`.
Switching back to `v2.2.1` solved my issues.
Should `v2.2.1` be left as @latest before 3.0 is out of alpha?
If this wasn't a mistake then please disregard!

**Comment by danigb** [comment]
Yes, my mistake! Sorry. I've republished 2.2.2 as latest and 3.0.0-alpha2 as alpha. Thanks for reporting! 👍
