### ISSUE TITLE
Tonal scale source/docs are outdated

### ISSUE THREAD

**Issue by kasbah** [danigb/tonal#13]
NPM has version `0.50.5` and the package.json on here says `0.50.0`. The docs seem to be outdated on both GitHub and NPM since there is no `scale.get` but a `scale.scale` function.

Thanks for this amazing library of useful bits!

**Comment by danigb** [comment]
I had vastly improved the documentation (https://danigb.github.io/tonal/api/) and now it's up to date to the code. 

Please free to reopen if you find some inconsistency.

Regards,
Dani
