### ISSUE TITLE
tonal.scaleRange behaving differently to range.scale

### ISSUE THREAD

**Issue by kasbah** [danigb/tonal#14]
With latest versions from NPM:

```
> range = require('tonal-ranges')
> range.scale('C D E F G A B', 'C3', 'C2')
[ 'C3', 'B2', 'A2', 'G2', 'F2', 'E2', 'D2', 'C2' ]
> tonal = require('tonal']
> tonal.scaleRange('C D E F G A B', 'C3', 'C2')
[ 'C3' ]
```

**Comment by danigb** [comment]
Hi @kasbah,

Thanks for reporting this issue. Unfortunately `tonal-ranges` is deprecated, but it can't be unpublished due the new policy from npmjs. I'm sorry for the name pollution (I've just added a deprecated warning). The actual library is called `tonal-range` (in singular).

The usage is:
```js
var range = require('tonal-range')
range.scaleRange('c d e f g a b', 'c3 c2') // => [ 'C3', 'B2', 'A2', 'G2', 'F2', 'E2', 'D2', 'C2' ]
```

Obviously is quite confusing, so I will try to improve the documentation (issue #13) or find a nice solution (so I'll keep this issue open)

Cheers,
Dani

**Comment by kasbah** [comment]
Thanks @danigb, the main problem seems to be that `tonal.scaleRange` is giving an invalid result though?

```
> tonal = require('tonal']
> tonal.scaleRange('C D E F G A B', 'C3', 'C2')
[ 'C3' ]
```

**Comment by danigb** [comment]
Well, the problem in fact is with the function signature. The range must be specified as a single string, so instead of: `scaleRange(..., 'C3', 'C2')` you have to write `scaleRange(...,'C3 C2')`

This was not a right decision, so I'll improve it too.

**Comment by kasbah** [comment]
Oh ok, it isn't it using `tonal-range` code itself?

**Comment by danigb** [comment]
Yes, `tonal.scaleRange` is the same function as `range.scaleRange`. The problem is in the documentation. I'll fix it ASAP.

**Comment by kasbah** [comment]
Ah I see, I think it was mainly [this documentation](https://github.com/danigb/tonal/tree/master/modules/range#scalerangenotes-start-end--array) which led me astray.

**Comment by danigb** [comment]
Exactly. But I think the function signature is more natural as the documentation says... I think it will accept both forms: `scaleRange(scale, range)` and `scaleRange(scale, start, end)`. I went with the first one for some reason I don't remember right now. I'll take a look and try to find a solution. Meanwhile you can use it as: `scaleRange(scale, range)`

**Comment by kasbah** [comment]
Thanks very much! If you are going to amend it though I just thought I'd mention how I am using it. Currently I grab scales from `tonal-scales` and then I have to bring them into the string format as well which is a little awkward. Maybe there is a better way to do this?

```js
const tonalScales = require('tonal-scales')
const tonalRange = require('tonal-range')

function getNotes(scale) {
    return tonalRange.range(tonalScales.scale(scale).join(' '), 0, 127)
}
```

**Comment by kasbah** [comment]
I had another thought about the original bug: why not just publish `tonal-ranges` to be the same as `tonal-range`?

**Comment by danigb** [comment]
I think all `tonal` functions accepts list of notes as strings or as arrays, so you don't have to do the convertion:

```js
var notes = tonalRange.range(tonalScales.scale(scale), 0, 127)
```

But again, I have a name pollution problem. The actual library is not `tonal-scales`but `tonal-scale`:

```js
var scale = require('tonal-scale')
var range = require('tonal-range')
var notes = range.scaleRange(scale.get('C major'), 'c2 c4')
```

I now this is confusing. I'll fix that too. I'm open to suggestions.

Thanks!

**Comment by danigb** [comment]
I like your solution with the npmjs names problem.

**Comment by kasbah** [comment]
Hey again, now `scaleRange` and other seems to have been removed from `tonal-range` 0.69 (even though it's still [documented in the README](https://www.npmjs.com/package/tonal-range#scaleRange))? I just tried to upgrade from 0.50. All the documented functions seem to be gone now. 


```
> require('tonal-range')
{ numeric: [Function: numeric],
  chromatic: [Function: chromatic],
  fifths: [Function: fifths],
  pitchSet: [Function: pitchSet] }
```
