### ISSUE TITLE
is there a client side release ?

### ISSUE THREAD

**Issue by b2renger** [danigb/tonal#16]
Hi @danigb 

cross-posting from this issue  : https://github.com/danigb/tonal.chord/issues/1

as I'm a bit confused, tonal-chord was usable client side, but it seems that tonal is nodejs based and supposed to run server-side am I right ? is there a client-side distribution ?

**Comment by danigb** [comment]
Yes, you can use the one from 'dist' folder

**Comment by b2renger** [comment]
I saw them but I cannot seem to get them working should I call an init function ?

I should be able to do something like :

```
chord('B7');
```

right away ? but I'm getting a "Uncaught ReferenceError: chord is not defined"

**Comment by danigb** [comment]
Is exported as `Tonal`:

```js
Tonal.chord('B7')
```

I hope it helps. Probably I should update the README.

**Comment by b2renger** [comment]
Great ! a capital 't' it is :)  and now I see where it is in the code : thanks !

There is a lot more functionalities here, it's quite impressive 1st_place_medal:

**Comment by danigb** [comment]
Thanks! Any suggestion, issue or PR are more than welcome.
