### ISSUE TITLE
progression.concrete() doens't recognize VII chords

### ISSUE THREAD

**Issue by ohmycode** [danigb/tonal#17]
@danigb I found a little bug:

`progression.concrete('I II III IV V VI VII', 'C')`

returns:
`['C', 'D', 'E', 'F', 'G', 'A', 'null']`

Love tonal, thanks for sharing!
Saludos 🍺

**Comment by danigb** [comment]
Hi! 

Good catch. Thanks! I hope it solved: https://github.com/danigb/tonal/blob/master/packages/progression/test/progression-test.js#L7

Un saludo

**Comment by danigb** [comment]
I've just published 0.68.1 with the fix. Thanks for the issue

**Comment by ohmycode** [comment]
perfect! thank you 👍
