### ISSUE TITLE
tonal.min.js

### ISSUE THREAD

**Issue by tatecarson** [danigb/tonal#28]
Hi, trying to use the minified js file and getting this error: 
```
Uncaught TypeError: Cannot read property 'toFreq' of undefined
    at tonal.min.js:1
    at tonal.min.js:1
    at tonal.min.js:1
```
Any advice?

**Comment by danigb** [comment]
Sorry, I didn't have time to test it before and... it's true! I'll try to fix it ASAP.
Thanks for reporting

**Comment by danigb** [comment]
It should be fixed now. Sorry for the inconveniences. Don't hesitate to reopen if the problem continues.
