### ISSUE TITLE
Deprecation on chord.detect question

### ISSUE THREAD

**Issue by thipages** [danigb/tonal#32]
Hi
When I log the example  `Tonal.chord.detect('g f# d b')`,
I got the following  warning ` pcset.chromaModes deprecated. Renamed to pcset.modes`

Sounds not so good... and a bit lost
How can I handle it?

Thank you

**Comment by danigb** [comment]
Yes... I've just pushed a 0.69.9 release that removes the warning. Thanks for reporting 👍

**Comment by thipages** [comment]
ok, fixed. Thank you.
By the way, it coud be interesting to have the version within the min.js
