### ISSUE TITLE
Chooords detection

### ISSUE THREAD

**Issue by thipages** [danigb/tonal#33]
I try to understand how to detect chords from a group of notes.
I am using the _simple method_ `Tonal.chords.detect(notes)
`
```
var test= [
   Tonal.chord.detect('g f# d b'),
   Tonal.chord.detect('g5 f5# d5 b5')
];
console.log(test);
```

Output:
```
["GMaj7"]
["GM","Bm#5"]
```
**Why dont we get the union of the two in each case?**

Note : if there is useful litterature/links on the subjects, I am willing to study it and try implemting something.

**Comment by danigb** [comment]
Hi @thipages, I have no idea of why this differences, in theory, the answer should be the same. I'll take a look as soon as possible.

**Comment by danigb** [comment]
Hi @thipages, I've found the error. In the second list of notes it should be f#5 instead of f5#. `tonal`silently ignores all that are notes (maybe thats not a good idea). 

The following code works:
```
tonal.chord.detect('g f# d b') // => ['GMaj7']
tonal.chord.detect('g5 f#5 d5 b5') // => ['GMaj7']
```
Please feel free to reopen if is not solved to you.

**Comment by thipages** [comment]
Oops! Sorry.
ok Thanks
