### ISSUE TITLE
Scale app: Cb drops and B# raized an octave

### ISSUE THREAD

**Issue by torqueville** [danigb/tonal#35]
Occurrences of note Cb in a scale in the scale app, drops one octave. Similarly any B# is raised an octave. Or so it seems, I did not check all the scales and keys, but found this: 

B# turns out to be raised in...
... E bebop major
... F# and A hungarian major
... E ionian augmented
...

Cb is dropped in... 
... Db, Eb, and Ab aolean
... Eb, Ab, and Bb balinese
... Db and Ab dorian  
... Db egyptian
... Ab flat three pentatonic
... Db hungarian major
... Eb and Bb kumoijoshi
...

**Comment by danigb** [comment]
That's really weird. I'll dig into this soon.

**Comment by danigb** [comment]
Hi @torqueville 

Probably too late to this party, but I think this is the intended behaviour. See: https://danigb.github.io/tonal-app/#/scale/bebop_major/E or https://danigb.github.io/tonal-app/#/scale/hungarian_major/A
