### ISSUE TITLE
Chords from intervals

### ISSUE THREAD

**Issue by Mdashdotdashn** [danigb/tonal#37]
I'm looking for a way to convert a set of intervals to the chords they make (the inverse of chord.intervals)

Instinctively I've tried `tonal.chord.detect('1P 3M 5P')` but it didn't work.

It looks like all the information is there but I'm not sure the api allows me to do this. Is there a clever way to do this I didn't see ?

Thanks !

**Comment by mrjacobbloom** [comment]
you could maybe do something like
```javascript
function intervalsToType(input) { // input = '1P 3M 5P'
  var input_array = input.split(' '); // -> ['1P', '3M', '5P']
  var chordInC_array = input_array.map(int => tonal.transpose('C4', int)); // -> ['C4', 'E4', 'G4']
  var chordInC_string = chordInC_array.join(' ');
  var chord = tonal.chord.parse(chordInC_string); // => {tonic: 'C', type: 'M'}
  return chord.type // 'M'
}
```
I haven't tested that but something along those lines might work

**Comment by danigb** [comment]
Thanks for the reply @mrjacobbloom :+1:

Just a note: tonal can work with arrays or strings, there's no need of conversion. So your code can be simplified to:

```
const input  = '1P 3M 5P'
tonal.chord.detect(tonal.harmonize(input, 'C')) // => ['CM', 'Em#5']
```

**Comment by mre-ableton** [comment]
Thanks !

**Comment by danigb** [comment]
Solution for tonal 1.0.0:

```js
const intervals = ["1P", "3M", "5P"];
const chroma = Tonal.PcSet.chroma(intervals);
Tonal.chord.names(chroma); // => ["M", "Maj"]
```
