### ISSUE TITLE
Deprecation warning when using note.alt() (v0.69.9)

### ISSUE THREAD

**Issue by lukehorvat** [danigb/tonal#38]
Hi. When doing `note.alt('C#2')`, I see the following warning:

> note.props() is deprecated. Use: note.step(), note.alt() or note.oct()

Am I doing something wrong?

**Comment by danigb** [comment]
Nothing wrong. It's something related to the new 1.0 API, but I must admit warning at the console was not a good idea (becuase `note.alt` is *not* deprecated, but it uses a deprecated function). 

I hope I can solve it soon.

Cheers

**Comment by danigb** [comment]
Fixed.
