### ISSUE TITLE
status of enharmonics?

### ISSUE THREAD

**Issue by devboell** [danigb/tonal#42]
I am a bit lost about where to find the old `tonal.note.enharmonics`. I see you made enharmonics package in extensions, but this is not in the final release? Do you plan to add it?

thanks

**Comment by danigb** [comment]
I'm not sure. Currently is lives in https://github.com/danigb/tonal-extensions and I'm planning to release separately when 1.0.0 is done. But I'm open to suggestions.

**Comment by danigb** [comment]
Currently, functions from `tonal-enharmonics` now lives inside `note` module (and `tonal-enharmonics` is deprecated):

- simplify: http://danigb.github.io/tonal/api/module-Note.html#.simplify
- enharmonic: http://danigb.github.io/tonal/api/module-Note.html#.enharmonic
