### ISSUE TITLE
enharmonics use case

### ISSUE THREAD

**Issue by devboell** [danigb/tonal#43]
I have a particular use case for enharmonics. I find enharmonics tricky because you can have more than one accidental. For my case I am only interested in getting the enharmonic for one accidental, and if the note has no accidental it should return the note itself. (I hope this makes sense).
for example:
C => C
C3 => C3
C# => Db
C#3 => Db3
Db3 => C#3

I made a method that could fit in tonal.note. I called it equiv (from equivalent), but that is probably not the right name.

```
export const equiv = (str) => {
  const a = alt(str)
  const s = step(str)
  const o = oct(str) || undefined // convert null to undefined
 
  return build({step: a + s, alt: -a, oct: o})
}
```

with two test cases:

```
test("equiv pc", () => {
    const FLATS = "C Db D Eb E F Gb G Ab A Bb B".split(" ");
    const SHARPS = "C C# D D# E F F# G G# A A# B".split(" ");
    const flatEquivs = FLATS.map(note.equiv)
    const sharpEquivs = SHARPS.map(note.equiv)
    expect(flatEquivs).toEqual(SHARPS)
    expect(sharpEquivs).toEqual(FLATS)
  });
```

```
  test("equiv pitch", () => {
    const FLATS = "C3 Db3 D3 Eb3 E3 F3 Gb3 G3 Ab3 A3 Bb3 B3".split(" ");
    const SHARPS = "C3 C#3 D3 D#3 E3 F3 F#3 G3 G#3 A3 A#3 B3".split(" ");
    const flatEquivs = FLATS.map(note.equiv)
    const sharpEquivs = SHARPS.map(note.equiv)
    expect(flatEquivs).toEqual(SHARPS)
    expect(sharpEquivs).toEqual(FLATS)
  });
```

I am not suggesting this should be in tonal, but I am curious what your thoughts are about this. Does this somehow correspond to a concept in music theory, or does it go against the logic of enharmonics, and maybe shouldn't be handled this way?

thanks

**Comment by danigb** [comment]
Hi,

I think this is an interesting concept,  but I have some question: why do you want the opposite alteration?. Thinking in loud, I find more convenient to select if you want flats or sharps and always get that kind of accidental. What is your use case? Also, does it work with more than one alteration? If so, some test would nice. If not, some restrictions should be in the code.

Anyway, I think your function is a good candidate to be in `tonal-enharmonics`. What I would like with tonal 1.0.0 is to provide a stable "core" and a good amount of extensions modules ;-). 

I don't know if the name `equiv` is a good one. I'm not sure about what is the utility so I can't think a good name (and naming thing is hard!)

Two small related things. First, In tonal 1.0 I'm trying to move from this kind of code: 

```js
const a = alt(str)
const s = step(str)
const o = oct(str)
```

To this one:

```js
const { alt, step, oct } = note.props(str);
```

Second, the conversion to `undefined` in `const o = oct(str) || undefined // convert null to undefined` I think shouldn't be necessary, so I will change `build` function to accept null or undefined.

What do you think about both changes?

**Comment by devboell** [comment]
It is for display purposes. I want to show the notes of a fretboard like:
C   C#/Db   D   D#/Eb   E   F   F#/Gb ... etc.
So it's independent of tonic or key.

I have the code like this:

```
// returns an array with the original note or two
// enharmonic notes ordered sharp first
export const enharmonics = note =>
  tonal.note.enharmonics(note).filter(enh =>
    note.length === enh.length,
  )


const formatSharp = sh => sh.replace('#', '\u266F')
const formatFlat = fl => fl.replace('b', '\u266D')


const displayNote = (pc) => {
  const enhs = enharmonics(pc)
  return enhs.length === 1
    ? enhs[0]
    : `${formatSharp(enhs[0])}/${formatFlat(enhs[1])}`
}
```

I now want to adapt to tonal 1.0, so the `equiv` function could be a part of it. Actually I may only need it for pc's, so another approach could be to make a fromChroma method (with a flat/sharp flag like you have for fromMidi), and use that as part of the algorithm.
  To handle multiple accidentals is a bit too advanced I think, and my own knowledge on that subject is a bit foggy.

  Equiv is a very bad name :-) ... when I have difficulty naming things, it's often a sign that I don't fully understand the concepts involved.

Anyway, I guess this case is a bit too specialised to include in tonal, but if you want to include it, then indeed I agree with the two modifications you suggest.

**Comment by devboell** [comment]
The old version of fretboard is here, in case you want to see:  https://fretboard-trainer.herokuapp.com/
 I wrote that last year and couldn't finish it. It was my first javascript/react app, and i am very unhappy with code quality. I am currently rewriting it.

**Comment by danigb** [comment]
What if there's a function `tonal.note.names ()` that returns that array of
notes directly?

And maybe we can integrate fretboard-trainer into tonal-app. What do you
think?

**Comment by devboell** [comment]
yes, tonal.note.names() would be very good.

I think tonal-app and fretboard-trainer have different purposes, so maybe not integration, but there could be some form of relationship. The future of fretboard-trainer is uncertain anyway. I have some time to work on it now, but I am also currently looking for a job and once I find one, I'll probably be too busy. I'll have to see how far I get with this rewrite ...

**Comment by danigb** [comment]
I've published a new version of tonal (1.0.0-pre4) with note.names() and
note.namesEnh()

And yes, I was thinking not in integration, but displaying scales and chord
fretboards inside tonal-app.

**Comment by devboell** [comment]
I am just wondering, are you sure you want it this way? I mean, you are now hardcoding the '/' in the grouped names, and it seems it is only for my requirement. Others might not want the '/'. And I would have to split too, because I want to format for html. And also, to get all the names in an array is not really suitable for how my app is now. I am just trying to think from the tonal perspective, and your wish to have a small api surface.
  It's up to you of course, but I am fine with waiting until you publish tonal-extensions, and then make a function in the enharmonics package.

  And for the fretboard, I see what you mean now. I am trying to make the fretboard component as reusable as possible, so hopefully it will be usable for tonal app. When I have something ready, I will let you know by creating an issue in the tonal-app repo.

**Comment by danigb** [comment]
Hi Rob,

yes, I was exploring some ideas. I've published a pre5 with some changes:

- I've removed the `namesEnh` function. Only `names`. https://github.com/danigb/tonal/tree/master/packages/note#module_note.names
- Similarly, I've added an `interval.names`
- I've added `simplify` and `enharmonic` to note-package

And yes, you're right, I was thinking in something like a reusable React Component that displays notes, chords, and scales (maybe using svg?) in a fretboard. I would like to have something like this and I'm open to working together if you want.

**Comment by devboell** [comment]
Ok, that sounds good. Right now I am focussed on the first phase of the fretboard app rewrite. Hopefully by next week I have something ready and I'll push to github. We can then discuss on how to break-out the fretboard component, and make it fully reusable. I will let you know!

**Comment by devboell** [comment]
Hi Dani,

Just to let you know that I haven't forgotten about the fretboard component. I've had some delays, but I am still working on it. Hopefully (again :-) ) I will have something this week.
