### ISSUE TITLE
creating note from abc notation

### ISSUE THREAD

**Issue by jisike** [danigb/tonal#44]
Are there any functions for creating a note from abc notation?

**Comment by danigb** [comment]
Currently there's no support for abc notation. If you mean convert a note from, for example "c" to "C5", it should be easy to implement using `note.build` function.  

What do you need this for?

**Comment by jisike** [comment]
I'm trying to computationally parse an abc string it into an object, manipulate it (ie change tones, pitch and etc) using tonal and convert it back into a string.

**Comment by danigb** [comment]
I've wrote the `tonal-abc-notation`: http://danigb.github.io/tonal/api/module-abc-notation.html

You can install it using npm. Hope it helps.

**Comment by jisike** [comment]
Thanks for the reply! How can I use that module in the browser?

**Comment by danigb** [comment]
You can use a tool that can convert from node modules to browser modules. I think the easiest one is browserify: http://browserify.org/

The other option is to use a tool like budo: https://github.com/mattdesl/budo. It's easier to get started, but after you will need to use browserify or something similar.

Hope it helps.

**Comment by jisike** [comment]
Thanks! I have Tonal running in the browser but now I'm not able to call functions from it in the console. Any tips?

**Comment by danigb** [comment]
If you are using the including the file from the `dist/` folder, like this: `<script src="tonal.min.js"></script>`, you can write at the console: `Tonal.midi('c4')` and it should work.

But abc-notation module is not included in the bundled file. So, to use it, you need to create a file like index.js with something like:

```
// use the Abc module standalone
const Abc = require("tonal-abc-notation");
console.log(Abc.toAbc("C#4"));

// use it with Tonal
const Tonal = require("tonal");
console.log(Tonal.Scale.notes("Bb major").map(Abc.toAbc));
```

and then use browserify to create a browser compatible version (and load that file with a `<script>` tag inside an html file). Hope it helps.

**Comment by jisike** [comment]
Thanks. As I mentioned I have it bundled using browserfiy and etc. I just asking if its possible to call functions in the console. If so how? Thanks again!

**Comment by danigb** [comment]
Yes, I don't know if I get you 😆 

You can open a console using the browser's developer tools, and write `Tonal.Scale.notes("C major")` and you will see the output (an array of notes). This just works.

**Comment by jisike** [comment]
It doesnt work for me. When I tried to call:

`Tonal.Scale.notes("C major")`

and I get this error:

```
VM2704:1 Uncaught ReferenceError: Tonal is not defined
    at <anonymous>:1:1
```

**Comment by danigb** [comment]
If you use the tonal.min.js dist file, it works out of the box. If you are transpiling your own sources, you must export the tonal facade inside your code: `window.Tonal = Tonal;` (and `window.Abc = Abc;` if you want to use it from the console)

Hope it helps!

**Comment by jisike** [comment]
Thanks that works! Also thanks for answering general JS questions! Can I ask one more: How would you recommend structuring the other vars and functions (that aren't in a class) to access in the same way? I tried using a closure but that didn't work.
