### ISSUE TITLE
404s in docs

### ISSUE THREAD

**Issue by shockey** [danigb/tonal#45]
Looks like there's a lot of missing pages in the GitHub.io docs 😕 

Is this a mistake, or is the documentation incomplete?

**Comment by danigb** [comment]
Yes, I see. I've regerated them and it works... almost. I don't know I still get a 404 on tonal-Chords (but the file exists: https://github.com/danigb/tonal/blob/master/docs/api/module-Chord.html)

I'll close the issue when fixed.
