### ISSUE TITLE
Proposal: add a 'set' function on tonal-note

### ISSUE THREAD

**Issue by holden-caulfield** [danigb/tonal#46]
First of all @danigb thanks for this awesome library. 

I'd like to propose a small addition that I would find useful. Adding a `set` function to the tonal-note module

The docs for such a function would be somewhat like this:

`(static, constant) set`

Given a note (string) and an object with props, return the note that results from overriding the given note with those props

Example:
`Note.set("C4", {alt: 1, oct: 3}) // => "C#3"`

Happy to make a PR with the change if you find it useful. I'm thinking the implementation of this as a combination of `build` and `props`

**Comment by danigb** [comment]
Hi @holden-caulfield 

It sounds like a very good idea and useful idea, but I'm reluctant to add new functions to the API if it's not strictly necessary. What If you change the `build` function signature to accept an optional parameter? What do you think? Any other idea?

Anyway, a PR of this will be highly appreciated! ;-)

Cheers

**Comment by holden-caulfield** [comment]
I've taken your suggestion of making it a part of `build`. 
Here's the PR, please check it out: https://github.com/danigb/tonal/pull/47/files

Thanks!

**Comment by danigb** [comment]
I'm closing this issue now the PR is merged. Feel free to reopen the discussion again :-)
