### ISSUE TITLE
Transposing through multiple octaves?

### ISSUE THREAD

**Issue by wildcat510** [danigb/tonal#49]
Hey there, thanks for the great library!

I'm wondering if there is a way to transpose a note through multiple registers (ex: C3 -> C5, etc) using Tonal.transpose(). 

I'm making an app that dynamically generates tables of numbers and assigns notes to the numbers using modular arithmetic. Note names are right, just need to find a way to scale them to their proper register :)

**Comment by danigb** [comment]
Hi @wildcat510 

Glad you like it. If I understand you, what you need is `Note.from`:

```js
Note.from({oct: 3}, "C4") // => "C3"
```

Hope it helps!

**Comment by wildcat510** [comment]
Perfect! Just launched Vedic.js v0.1.0 using Note.from() to scale the range.
https://github.com/wildcat510/Vedic.js

**Comment by danigb** [comment]
Great! I don't understand what a Vedic square is, but I'll take a look.
