### ISSUE TITLE
Tonal.transpose() returns scale with notes in wrong register

### ISSUE THREAD

**Issue by wildcat510** [danigb/tonal#50]
Working beautifully on my app in the key of C. Registral errors occurring when tranposing to other keys. Console logged some of these out:

Interval structure returned is correct.
`myscale = Tonal.scale('major');`
=>["1P", "2M", "3M", "4P", "5P", "6M", "7M"]

Great in the key of C.
`myscale.map(Tonal.transpose('C2'));`
=>["C2", "D2", "E2", "F2", "G2", "A2", "B2"]

We start to see registral problems when transposing to other keys.
`myscale.map(Tonal.transpose('D2'));`
=> ["D2", "E2", "F#2", "G2", "A2", "B2", **"C#3"**]

`myscale.map(Tonal.transpose('E2'));`
=> ["E2", "F#2", "G#2", "A2", "B2", **"C#3", "D#3"**]

etc...

Can't wait to introduce this functionality to my app! Thanks again!

**Comment by danigb** [comment]
Hi @wildcat510 

Thanks for reporting! 👍 

But, as far as I know, this is the expected output. For example, "D2" transposed by a "7M" is "C#3"... The same can be applied to "E2" transposed by a "6M" or a "7M". In fact, "E2 major" is exactly the scale you obtained.

Am I missing something?

Regards,
Dani

**Comment by wildcat510** [comment]
A major 7th above D2 is C#2 in the same register— just like in the example in C, a major 7th above C2 is B2 in the same octave. If I'm transposing a C scale (or any scale) in octave register 2 to another key, the whole scale should stay in the same octave register unless I'm using the wrong method for transposing keys. All scales should be played linearly, steps 1 through 7, not steps 1-6 and then 7 an octave higher, or 1-5 with 6 and 7 and octave higher.

So just like `myscale.map(Tonal.transpose('C2'));` produces `["C2", "D2", "E2", "F2", "G2", "A2", "B3"]`, a uniform linear scale played from scale degree 1 to 7, I would expect the same of other keys. 

 Unless I'm missing something. Is this the right way to go about transposing scales as an entire unit to a different key?

**Comment by mrjacobbloom** [comment]
The cutoff for register number is always C no matter what key you're in. C# above D2 is higher than the C that follows D2 so it's in the 3rd register. C#2 is the note below D2

**Comment by wildcat510** [comment]
So is there any way I can have scales in keys other than C laid out in a register theoretically consistent with the same way a musician would notate and play it?

**Comment by danigb** [comment]
Hi!

Yes, I think @mrjacobbloom is right here. In western music theory we use always C as the cutoff registry.

Another way to think about it is using interval sizes. For example, 7M is 11 semitones up. That's exactly the distance from D2 to C#3 (and the distance from D2 to C#2 is 1 semitone down).

I don't understand very well your explanation, @wildcat510 but It would help to have some external references or resources.

Anyway, you can always use _pitch classes_ (note names without octave number) to avoid this problem:

```js
["1P", "2M", "3M", "4P", "5P", "6M", "7M"].map(Tonal.transpose("D")) // => ["D", "E", "F#", "G", "A", "B", "C#"]
```

And you can use `Tonal.Note.props` to coerce to an octave: `scale.map(note => Tonal.Note.props({ oct: 2 }, note))` or, if you are sure they are all pitch classes, a simple string concatenation: `scale.map(note => note + "2")`

Hope it helps
Regards
Dani

**Comment by wildcat510** [comment]
Looks like I misunderstood the transpose function's application. Concatenating pitch classes works. 
Thanks guys!
-Nate

**Comment by danigb** [comment]
Great! I'm going to close this issue, but feel free to reopen if something is not clear.
