### ISSUE TITLE
Converting Scale.notes results to midi values

### ISSUE THREAD

**Issue by JamesJefferyUK** [danigb/tonal#51]
I can't seem to figure out how to convert the results from `Scale.notes('Bb lydian')` to MIDI values.

The results from `Scale.notes('Bb lydian')` are in the form `["Bb", "C", "D" ...]`. There's no pitch data . This is causing an issue because I need the MIDI values of this scale. `midi(...)` doesn't seem to work unless there's a pitch associated with the note.

I have also tried `toNote` from `tonal-abc-notation` but the following fails: `toNote("Bb")`. It returns `null` for the flat notes. Not sure if that's a bug or intended.

Is there an easier way to get the scale values as midi number as opposed to ABC strings?

**Comment by danigb** [comment]
Yes, the problem is that you are using pitch classes (notes without octaves). 

You should write (notice the 4 after the note name):

```js
Scale.notes("Bb4 lydian").map(Note.midi)
```

Hope it helps. Feel free to reopen if needed.
