### ISSUE TITLE
aug\Dom\dim chords can't get notes

### ISSUE THREAD

**Issue by mahavira** [danigb/tonal#52]
hi @danigb 
The problem was discovered a week later.
aug\Dom\dim chords can't get notes
```
Chord.notes("Caug") // []
Chord.notes("C","aug") // []
``` 

I've found that this function does a little bit more processing
```
Chord.tokenize("aug") // ["A", "ug"]
```

`tokenize`This function is executed twice
```
...
export const intervals = name => props(tokenize(name)[1]).intervals;
export function notes(nameOrTonic, name) {
  const p = tokenize(nameOrTonic);
  name = name || p[1];
  return intervals(name).map(transpose(p[0]));
}
```

**Comment by danigb** [comment]
Hi @mahavira, thanks for reporting. I'll take a look at this issue soon.

**Comment by danigb** [comment]
I think it's solved and I've published a new version. Thanks to your research, solve the issue was trivial. Thanks! 👍

**Comment by rowild** [comment]
@mahavira It seems "chord('alt7')", "chord('dim')" and "chord('dim7')" do not generate a proper object (chroma, pcset, intervals... missing)
