### ISSUE TITLE
the results are different by 'Chord.tokenize'

### ISSUE THREAD

**Issue by mahavira** [danigb/tonal#55]
hello again
```
Tonal.Chord.tokenize('C11')  // ["C11", ""]
Tonal.Chord.tokenize('aug')  // ["A", "ug"]
```
The following functions are also associated.
`Chord.intervals`
```
Tonal.Chord.intervals('C13no5') // []
Tonal.Chord.intervals('aug') // []
```

**Comment by danigb** [comment]
Hi @mahavira 

Thanks again for reporting. I've published a v1.1.3 that fixes this issue. Please feel free to reopen if you find more edge cases.
