### ISSUE TITLE
Issues with Note.midi

### ISSUE THREAD

**Issue by apalm** [danigb/tonal#58]
As requested by @danigb in https://github.com/danigb/tonal/pull/57#issuecomment-358780617

https://github.com/danigb/tonal/pull/57 addresses two main issues with `Note.midi`.

First, it fixes a few bugs with the current `Note.midi` implementation:

* `Note.midi(0)` returns `null`. It should return `0`.
* `Note.midi("c-1")` returns `null`. It should return `0`.
* `Note.midi(true)` returns `1`. It should return `null`.

Second, it changes `Note.midi` to only return numbers in the range of 0 to 127. Currently, `Note.midi` returns numbers outside this range, which I consider to be a bug. For example:

* `Note.midi(128)` returns `128`. It should return `null`.

Does that make sense?

**Comment by scraggo** [comment]
+1 this issue. Let me know if there's a way I can help. @apalm

**Comment by danigb** [comment]
Yes, sorry the (huge) delay. Merged. Thanks a lot @apalm  🙏

**Comment by danigb** [comment]
Hi! 

Finally, I've made some changes to your PR. First of all, `props('C4')` behaves as before (midi note numbers can be outside range 0 to 127). And `note.midi('C4')` always returns a value inside that range. Since it's a breaking change, I've pump tonal version to 2.0.0
