### ISSUE TITLE
How do you transpose down?

### ISSUE THREAD

**Issue by davidlav** [danigb/tonal#59]
I want to transpose notes an octave down and tried `tonal.transpose(note, '-P8');` but that didn't work and I couldn't find anything in the docs pertaining to _direction_ of the interval you wish to transpose by.

**Comment by danigb** [comment]
It works for me:

```js
const Tonal = require('tonal');
Tonal.transpose('C4', 'P-8') // => 'C3'
// or 
Tonal.Distance.transpose('Db5', 'P-5') // => 'Gb4'
```

**Comment by davidlav** [comment]
Perfect, thanks.  I never would have thought to put the minus sign _between_ the letter and the number.  Could you add that to the documentation?  Thanks!

**Comment by danigb** [comment]
It's documented, but a little bit hidden: https://github.com/danigb/tonal/tree/master/packages/interval#interval

Two different notations are supported.

Suggestions or PR welcomed ;-)

**Comment by davidlav** [comment]
Ah, I see it now.  Thanks for such a great library, fantastic work!!
