### ISSUE TITLE
Key.triads is not working

### ISSUE THREAD

**Issue by rickdps** [danigb/tonal#80]
**Describe the bug**
When I call Key.triads("A major"); I get: 

TypeError: Key.triads is not a function

**To Reproduce**
1. const Key = require("tonal-key");
2. Key.triads("A major");

When the above code is run I get: 
TypeError: Key.triads is not a function

If I call Key.chords("A major") it works fine.

Any help will be greatly appreciated.

**Comment by rakannimer** [comment]
Hey @rickdps 

I think this is happening because triads code has not been published to npm yet. 

You can find the currenly published package code here : https://unpkg.com/tonal-key

Cheers !

**Comment by rickdps** [comment]
Thank you for the quick reply. I have checked the package code you gave me but triads function is not in it. 
Maybe you forgot something?

**Comment by danigb** [comment]
Sorry, forgot to published. Version 2.1.0 is out. Remember, `tonal-key` is an extension, so must be installed separately: `yarn add tonal-key` or `npm install tonal-key`. Then:

```js
const Key = require('tonal-key');
Key.triads('A major');
```

Hope it helps!

**Comment by rickdps** [comment]
Thank you so much!
