### ISSUE TITLE
Chord.note issue using root of C6 or above

### ISSUE THREAD

**Issue by sandianstudio** [danigb/tonal#82]
I'm generating chord notes using Chord.notes("C4", "m11"). This works fine up to the sixth octave i.e. C6. From C6 and above, the returned array omits the octave:

Chords.notes("C5", "m11") returns ["C5","Eb5","G5","Bb5","D6","F6"]
Chords.notes("C6", "m11") returns ["C","Eb","G","Bb","D","F"]

Thanks in advance!
(By the way, Scale.notes above the sixth octave works fine.)

**Comment by danigb** [comment]
Hi, 

Should be fixed in v2.1.2.

Thanks for reporting! 👍

**Comment by sandianstudio** [comment]
That did the trick! Thanks for the quick fix.
