### ISSUE TITLE
How do I use extensions in browser?

### ISSUE THREAD

**Issue by DvDream** [danigb/tonal#85]
Hi, How can I use the extension using the Browser? Because for "tonal.min.js" functions everything works fine with the global object "Tonal", but when I try the example from the doc, i.e in detect:

import { chord } from "tonal-detect"
console.log(chord(["C", "E", "G", "A"])) // => ["CM6", "Am7"]

the console prints out: "Uncaught SyntaxError: Unexpected token import"

Can somebody help me please? Thanks!

**Comment by danigb** [comment]
Hi @DvDream,

I'm afraid you have to use a tool to convert your code to something that browsers understand. The easiest way I know is to use [parcel](https://parceljs.org/). Other alternatives are browserify, rollup or webpack (in order of complexity).

The general idea is to create a file with .js extension that imports the code (the same way you did above) and then use the tool to convert that into another .js file compatible with browsers.

Here is an example with browserify: https://github.com/browserify/browserify#example

This is more a tutorial: https://medium.com/@tkssharma/browserify-for-loading-common-js-modules-b0d73791afa6

Hope it helps!

**Comment by DvDream** [comment]
> Hi @DvDream,
> 
> I'm afraid you have to use a tool to convert your code to something that browsers understand. The easiest way I know is to use [parcel](https://parceljs.org/). Other alternatives are browserify, rollup or webpack (in order of complexity).
> 
> The general idea is to create a file with .js extension that imports the code (the same way you did above) and then use the tool to convert that into another .js file compatible with browsers.
> 
> Here is an example with browserify: https://github.com/browserify/browserify#example
> 
> This is more a tutorial: https://medium.com/@tkssharma/browserify-for-loading-common-js-modules-b0d73791afa6
> 
> Hope it helps!

Thank you! I'm using parcel now and I solved my problem!! :D
