### ISSUE TITLE
Chords from degrees (chord progressions)

### ISSUE THREAD

**Issue by vellebelle** [danigb/tonal#89]
Hi @danigb, thanks for your excellent work on tonal.js. 

First of all I'm not sure if this is the right place to ask questions, or if there's a support forum somewhere else? I hope it's ok to ask here though.

I would like to know if it's possible to create a set of chords from chord degrees. I have looked in the Key extension, and I can see this example:

`Key.degrees("C major") => ["I", "ii", "iii", "IV", "V", "vi", "vii"]`

But what if I want to get chords from the chord degrees I input?

For example if I want the chords for a ii V I progression and I want it to be in the key of C. Something like this:

`chordsFromDegrees(['ii', 'V', 'I'], 'Cmaj7') // ['Dm7', 'G7', 'Cmaj7']`

 Is that somehow possible?

**Comment by danigb** [comment]
Well... I don't think so. It used to be a module to parse roman numerals, but I think I've lost it in some refactor :-(  

I think I'd be a good addition. I'll try to implement it, but PR are welcomed, too

**Comment by danigb** [comment]
Here you have it: https://danigb.github.io/tonal/module-Key.html#.chords

(you have to update tonal-key)

Hope it works!

**Comment by vellebelle** [comment]
Wow. That was fast.. Amazing! And thank you very much.. I'll check it out this weekend an see if I can get it to work 👍

**Comment by vellebelle** [comment]
It works perfectly.. Thanks again!
